---
title: "**MC06** *Introdução a modelos lineares e à inferência causal em ecologia*"
output:
  html_document:
    number_sections: false
    toc: true
    theme: yeti
    toc_depth: 3
    toc_float: 
      collapsed: false
      smooth_scroll: false
---

# Preliminares

## R

Inicialmente, você deve instalar o **R** no seu computador. 
Você pode encontrá-lo no sítio <http://www.r-project.org>.
Neste sítio existem instruções (em inglês) para instalá-lo em vários sistemas operacionais diferentes; versões para Windows, Mac OS e Linux estão disponíveis.
Em suma, vá a um dos espelhos do *Comprehensive R Archive Network* (CRAN), por exemplo <http://brieger.esalq.usp.br/CRAN/>, e siga os links de download e instale o pacote referente ao seu sistema operacional.
Usuários de Linux provavelmente possuem um gerenciador de pacotes instalado em seu sistema, como por
exemplo *apt* ou *dnf*, que podem também ser utilizados para a instalação.

A instalação básica do R no Windows ou MAC OS providencia uma interface básica para execução de rotinas; no entanto, recomendamos a instalação do **R Studio**, uma interface bastante intuitiva para
utilizarmos o R. 
Esta interface pode ser encontrada no sítio <http://www.rstudio.com> para Windows, MAC OS ou Linux.

O curso foi pensado para pessoas que não são familiarizadas com o R; não esperamos que você seja, a princípio, capaz de escrever rotinas na linguagem. 
Os tutoriais propostos se baseiam em rotinas prontas, uma para cada aula, de modo que estes exercícios consistem em executar estas rotinas, observar e entender o que foi feito, e responder algumas perguntas. 
Assim, estes exercícios servem como ponto de partida para você começar a entender a linguagem. 
Durante o curso, nós vamos introduzir alguns conceitos que são cruciais para o entendimento das rotinas que estamos disponibilizando aqui.

Se você quiser começar a entender a linguagem antes do curso iniciar, recomendamos o sítio <http://ecor.ib.usp.br/doku.php>, da disciplina básica de R oferecida pelo Departamento de Ecologia do IB-USP. 
O link "Atividades Preparatórias" oferece um introdução da linguagem.

# Aulas Teóricas

## Primeiro dia

- **Aula 1**: Introdução e Modelos lineares simples ([slides](slides/ModelosLineares.pdf))
- **Aula 2**: Modelos lineares múltiplos, transformação e interações ([slides](slides/ModelosLinearesMultiplos.pdf))


## Segundo dia

- **Aula 3**: Introdução à inferência causal ([slides](slides/CausalPensamento.pdf))

# Tutoriais

- Tutorial 1: [Modelos lineares simples](tutoriais/lab.html)
- Tutorial 2: [Modelos lineares múltiplos](tutoriais/lab2.html)
- Tutorial 3: [Introdução à inferência causal](tutoriais/PensamentoCausal.html)

# Material de apoio

Esse curso é baseado no curso de modelagem estatística oferecido na formação em ecologia teórica de Serrapilheira. O site do curso de anos passados está abaixo e tem muitas referências, outras aulas, e tutoriais. 

- [2023 course website](https://statistical-inference.netlify.app/)
  - [Video lectures](https://www.youtube.com/results?search_query=QEco+Program%3A+Statistical+models)
- [2024 course website](https://statistical-modeling.github.io/2024/) 